name: air.yaml

on:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: r-hub/actions/format-r-code@main
    - run: git diff
      shell: bash
